name: Node Continuous Integration

on:
  pull_request:
    branches: 
      - dev6 
jobs:
    test_pull_request:
      name: Running Unit Tests
      runs-on: macos-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 15
        run:
        - cd demo
        - npm install
        - npm test

