name: Node Continuous Integration

on:
  pull_request:
    branches: [ dev6 ]
defaults:
  run:
    working-directory: demo
jobs:
    test:
      name: Running Unit Tests
      runs-on: macos-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 15
        run: |
        cd client
        npm install
        npm test


