name: Node Continuous Integration

on:
  pull_request:
    branches: [ Dev5 ]
defaults:
  run:
    working-directory: ./demo
jobs:
    test:
      name: Running Unit Tests
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 15
        - run: npm test


